---
require:
  - rubocop-rails
  - rubocop-rails
  - rubocop-rspec
  - rubocop-faker

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
