---
require:
  - rubocop-rails
  - rubocop-rails
  - rubocop-rspec
  - rubocop-faker

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - "db/migrate/*.rb"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*.rb"

Metrics/BlockLength:
  Exclude:
    - config/environments/*.rb
    - Gemfile

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/Focus:
  AutoCorrect: false
